<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BYOD-663311" failures="1" tests="3" name="Test1" time="21.495" errors="0" timestamp="2024-08-12T11:49:48 IST">
  <testcase classname="day2.ParallelTestingDemo" name="logo" time="0.075"/>
  <testcase classname="day2.ParallelTestingDemo" name="title" time="0.022"/>
  <testcase classname="day2.ParallelTestingDemo" name="url" time="0.016">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at day2.ParallelTestingDemo.url(ParallelTestingDemo.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- url -->
</testsuite> <!-- Test1 -->
